version: 2
updates:
  # This configures npm updates for the root package and all workspace packages.
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":arrow_up: chore"
      include: "scope"
    groups:
      npm-monorepo:
        patterns:
          - "*"
        group-by: "dependency-name"
