global: &global
  - '.github/path-filters.yml'
  - '.github/workflows/validate.yml'

gui:
  - *global
  - 'packages/gui/**'
  - 'packages/l10n/**'
  - 'packages/paint/**'
  - 'packages/storage/**'

paint:
  - *global
  - 'packages/paint/**'

storage:
  - *global
  - 'packages/storage/**'

vm:
  - *global
  - 'packages/vm/**'
  - 'packages/storage/**'
  - 'packages/parser/**'

render:
  - *global
  - 'packages/render/**'

parser:
  - *global
  - 'packages/parser/**'

block:
  - *global
  - 'packages/block/**'
