packages:
  - packages/*

catalog:
  jest: ^30.3.0
  react: 16.2.0
  typescript: ^5.9.3
  webpack: ^5.105.4

onlyBuiltDependencies:
  - chromedriver
  - core-js
  - gifsicle
  - jpegtran-bin
  - optipng-bin
  - playwright-chromium
  - unrs-resolver

overrides:
  cheerio: 1.0.0-rc.12

patchedDependencies:
  jsdom@26.1.0: patches/jsdom@26.1.0.patch
