packages:
  - packages/*
  - app/*

catalog:
  jest: ^30.3.0
  react: 16.2.0
  rule-inheritance-webpack-plugin: ^0.5.2
  typescript: ^5.9.3
  webpack: ^5.105.4

onlyBuiltDependencies:
  - chromedriver
  - core-js
  - electron
  - electron-winstaller
  - playwright-chromium
  - unrs-resolver

overrides:
  cheerio: 1.0.0-rc.12

patchedDependencies:
  jsdom@28.1.0: patches/jsdom@28.1.0.patch
