import {
  app,
  session,
  BrowserWindow,
  Menu,
  dialog,
  MessageBoxOptions,
  net,
  protocol
} from 'electron';


import path from 'node:path'
import fs from 'node:fs/promises';
import { ipcMain } from 'electron-better-ipc';
import argv from './utils/argv';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const SPLASH_WINDOW_WEBPACK_ENTRY: string;
declare const ABOUT_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

Menu.setApplicationMenu(null);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

protocol.registerSchemesAsPrivileged([
  { scheme: 'gui', privileges: { bypassCSP: true, secure: true} },
  { scheme: 'icons', privileges: { bypassCSP: true, secure: true}}
])


const initialProjectDataPromise = (async () => {
  if (argv._.length === 0) {
    // no command line argument means no initial project data
    return {projectData: null, projectName: ''};
  }
  if (argv._.length > 1) {
    console.warn(`Expected 1 command line argument but received ${argv._.length}.`);
  }
  const projectPath = argv._[argv._.length - 1];
  const projectData = await fs.readFile(projectPath);
  const projectName = projectPath.split('/')[-1]
  return {projectData, projectName};
  // load failed: initial project data undefined
})(); // IIFE

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1280,
    show: false,
    useContentSize: true,
    title: 'ClipCC',
    webPreferences: {
      // nodeIntegration: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });
  const splashWindow = new BrowserWindow({
    width: 300,
    height: 300,
    frame: false,
    resizable: false,
    titleBarStyle: 'hiddenInset'
  })

  const aboutWindow = new BrowserWindow({
    width: 350,
    height: 450,
    show: false,
    modal: true,
    resizable: false,
    parent: mainWindow,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    }
  })

  aboutWindow.loadURL(ABOUT_WINDOW_WEBPACK_ENTRY);
  splashWindow.loadURL(SPLASH_WINDOW_WEBPACK_ENTRY);
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.webContents.once('did-finish-load', () => {
    splashWindow.close();
    mainWindow.show();
    mainWindow.focus()
  });
  mainWindow.webContents.on('will-prevent-unload', ev => {
    const choice = dialog.showMessageBoxSync(mainWindow, {
      type: 'question',
      message: 'Leave ClipCC?',
      detail: 'Any unsaved changes will be lost.',
      buttons: ['Stay', 'Leave'],
      cancelId: 0, // closing the dialog means "stay"
      defaultId: 0 // pressing enter or space without explicitly selecting something means "stay"
    });
    const shouldQuit = (choice === 1);
    if (shouldQuit) {
      ev.preventDefault();
    }
  });
  // Open the DevTools.
  mainWindow.webContents.on('before-input-event', (event, input) => {
    if (input.key === 'F12') {
      mainWindow.webContents.openDevTools();
      aboutWindow.webContents.openDevTools();
    }
  })

  aboutWindow.on('close', event => {
    event.preventDefault()
    aboutWindow.hide()
  })

  ipcMain.handle('dialog:show', (event, options: MessageBoxOptions) => dialog.showMessageBox(mainWindow, options))

  ipcMain.answerRenderer('electron:getVersion', () => {
    return app.getVersion()
  })

  ipcMain.handle('gui:get-initial-file', () => initialProjectDataPromise);


  ipcMain.handle('gui:open-about', () => {
    aboutWindow.setMaximizable(false)
    aboutWindow.setMinimizable(false)
    aboutWindow.show()
  });


  ipcMain.handle('app:get-version', () => app.getVersion())
  ipcMain.handle('app:get-app-info', () => ({
    component: process.versions,
    appVersion: app.getVersion(),
    isPackaged: app.isPackaged
    
  }))
  ipcMain.handle('app:get-gpu', () => app.getGPUInfo('basic'))

  session.defaultSession.protocol.handle('gui', request => {
    const fileUrl = request.url.replace('gui://', '');
    const filePath = path.join(app.getAppPath(), '.webpack/gui', fileUrl);
    return net.fetch(filePath);
  });
  session.defaultSession.protocol.handle('icons', request => {
    const fileUrl = request.url.replace('icons://', '');
    const filePath = path.join(app.getAppPath(), '.webpack/icons', fileUrl);
    return net.fetch(filePath);
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});