name: Lint

on:
  workflow_dispatch:

jobs:
  build:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

  gui:
    name: Lint GUI
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm gui lint

  vm:
    name: Lint VM
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm vm lint:js

  block:
    name: Lint Block
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm block lint

  audio:
    name: Lint Audio
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm audio lint

  l10n:
    name: Lint l10n
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm l10n lint:js

  lint-config:
    name: Lint Lint Config
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm lint-config test

  paint:
    name: Lint Paint
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm paint lint

  parser:
    name: Lint Parser
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm parser lint

  render:
    name: Lint Render
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm render lint

  storage:
    name: Lint Storage
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: pnpm storage lint
