name: Pull Translation

on:
  workflow_dispatch:

jobs:
  pull:
    name: Pull Translation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps

      - name: Pull Translation
        run: yarn run translation:pull
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Push Commit
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          commit-message: ':globe_with_meridians: chore(l10n): pull translation from remote'
          files: packages/l10n/editor/
          name: clipbot
