name: Pull Translation

on:
  workflow_dispatch:

jobs:
  pull:
    name: Pull Translation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install and pull
        run: yarn install --frozen-lockfile && yarn run translation:pull
        env:
          POE_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Push Commit
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          commit-message: ':wrench: chore(l10n): pull translation from remote'
          files: packages/l10n/locales/ packages/block/msg/scratch_msgs.js
          name: clipbot
          email: cuizhihui030925@gmail.com