name: Validate

on:
  push:
    branches:
      - master
      - 'dev/**'
      - community
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build all packages
        run: yarn run build:full

      - name: Check types
        id: check-types
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            if [[ "${{ github.base_ref }}" == "master" ]]; then
              echo "should-run-all=true" >> $GITHUB_OUTPUT
            else
              echo "should-run-all=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "should-run-all=true" >> $GITHUB_OUTPUT
          fi

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            gui:
              - 'packages/gui/**'
              - 'packages/l10n/**'
              - 'packages/paint/**'
              - 'packages/storage/**'
            vm:
              - 'packages/vm/**'
              - 'packages/storage/**'
            block:
              - 'packages/block/**'

      - name: Test GUI
        if: steps.changes.outputs.gui == 'true' || steps.check-types.outputs.should-run-all == 'true'
        run: yarn gui test:unit

      - name: Test VM
        if: steps.changes.outputs.vm == 'true' || steps.check-types.outputs.should-run-all == 'true'
        run: yarn vm test

      - name: Test Block
        if: steps.changes.outputs.block == 'true' || steps.check-types.outputs.should-run-all == 'true'
        run: yarn block test
